# ACI playbook - Create Tenant - Includes network, security, and application profiles
---
- name: Create Development Tenant
  hosts: apic
  gather_facts: no

  vars_files:
    - dev_tn_variables.yaml

  roles:
    - role: cisco_aci_tenant
      data: "{{ aci }}"
