---
# Command to run the rulebook with specified inventory and rulebook file, printing events as they occur.
# ansible-rulebook -i inventory/hosts.yml  -r rulebooks/01_understand_rulebook.yml --print-events

- name: Basic Rulebook
  # Define the hosts group from the inventory where this rulebook will apply.
  hosts: automation_vm
  
  sources:
    # Define the source of events, in this case, a webhook that listens on all interfaces at port 8080.
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8080

  rules:
    # Rule to catch events with a specific payload data "Ciao".
    - name: Catch Ciao
      # Check if the data in the event payload equals "Ciao".
      condition: |
        event.payload.data == "Ciao"
      action:
        # Action to take when the condition is met: run a specific playbook.
        run_playbook:
          # Name of the playbook to execute when the condition is true.
          name: playbooks/01_reply.yml

    # Rule to print the event payload if the meta information is defined.
    - name: Print Event Payload
      # Check if the metadata of the event is defined. This is always True and can be used for debugging the event data.
      condition: |
        event.meta is defined
      action:
        # Action to take when the condition is met: print the event payload for debugging purposes.
        debug: