---
- name: mil-cml-vxlan-fabric-1 Initial Provisioning
  gather_facts: false
  hosts:
    - ndfc02
  vars:
    fabric_name: mil-cml-vxlan-fabric-1
    fabric_mtu: "9216"
    fabric_asn: "65701"
    site_id: "1"
    bbgw1: 172.23.254.143
    bbgw2: 172.23.254.144
    leaf1: 172.23.254.145
    leaf2: 172.23.254.146
    leaf50: 172.23.254.148
    leaf3: 172.23.254.147
    spine1: 172.23.254.141
    spine2: 172.23.254.142
  tasks:
    - name: Create / Update fabrics
      cisco.dcnm.dcnm_fabric:
        state: replaced
        skip_validation: False
        config:
        -   FABRIC_NAME: "{{ fabric_name }}"
            FABRIC_TYPE: VXLAN_EVPN
            BGP_AS: "{{ fabric_asn }}"
            UNDERLAY_IS_V6: false
            # Replication
            REPLICATION_MODE: Multicast
            # vPC
            VPC_DOMAIN_ID_RANGE: 100-199
            # Advanced
            GRFIELD_DEBUG_FLAG: "Enable"
            ENABLE_NXAPI: true
            SNMP_SERVER_HOST_TRAP: false
            # Resources
            LOOPBACK0_IP_RANGE: "{{ site_id }}0.1.1.0/24"
            LOOPBACK1_IP_RANGE: "{{ site_id }}0.1.2.0/24"
            ANYCAST_RP_IP_RANGE: "{{ site_id }}0.1.3.0/24"
            SUBNET_RANGE: "{{ site_id }}0.1.4.0/24"
            DCI_SUBNET_RANGE: "{{ site_id }}0.1.5.0/24"
            PER_VRF_LOOPBACK_AUTO_PROVISION: true
            PER_VRF_LOOPBACK_IP_RANGE: "{{ site_id }}0.1.5.0/24"
            VRF_LITE_AUTOCONFIG: Back2Back&ToExternal
            AUTO_SYMMETRIC_VRF_LITE: true
            AUTO_UNIQUE_VRF_LITE_IP_PREFIX: true
            # Management
            DNS_SERVER_VRF: management
            NTP_SERVER_VRF: management
            DNS_SERVER_IP_LIST: "10.58.30.68"
            NTP_SERVER_IP_LIST: "10.58.30.171"
            DEPLOY: true
      tags:
        - fabrics
    - name: Discover and Add switches
      cisco.dcnm.dcnm_inventory:
        fabric: "{{ fabric_name }}"
        state: merged
        config:
          - seed_ip: "{{ leaf1 }}"
            auth_proto: MD5
            user_name: "{{ device_username }}"
            password: "Cisco123!"
            max_hops: 0
            role: leaf
            preserve_config: false
          - seed_ip: "{{ leaf2 }}"
            auth_proto: MD5
            user_name: "{{ device_username }}"
            password: "Cisco123!"
            max_hops: 0
            role: leaf
            preserve_config: false
          - seed_ip: "{{ leaf3 }}"
            auth_proto: MD5
            user_name: "{{ device_username }}"
            password: "Cisco123!"
            max_hops: 0
            role: border
            preserve_config: false
          - seed_ip: "{{ spine1 }}"
            auth_proto: MD5
            user_name: "{{ device_username }}"
            password: "Cisco123!"
            max_hops: 0
            role: spine
            preserve_config: false
          - seed_ip: "{{ spine2 }}"
            auth_proto: MD5
            user_name: "{{ device_username }}"
            password: "Cisco123!"
            max_hops: 0
            role: spine
            preserve_config: false
          - seed_ip: "{{ bbgw1 }}"
            auth_proto: MD5
            user_name: "{{ device_username }}"
            password: "Cisco123!"
            max_hops: 0
            role: border_gateway
            preserve_config: false
          - seed_ip: "{{ bbgw2 }}"
            auth_proto: MD5
            user_name: "{{ device_username }}"
            password: "Cisco123!"
            max_hops: 0
            role: border_gateway
            preserve_config: false  
      tags:
        - devices
    - name: Recalculate
      cisco.dcnm.dcnm_rest:
        method: POST
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/config-save"
        json_data: "{{ {} | to_json }}"
    - name: Deploy
      cisco.dcnm.dcnm_rest:
        method: POST
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/config-deploy"
        json_data: "{{ {} | to_json }}"
    - name: Create VPC Pair
      cisco.dcnm.dcnm_vpc_pair:
        src_fabric: "{{ fabric_name }}"
        deploy: true
        state: merged
        config:
          - peerOneId: "{{ leaf1 }}"
            peerTwoId: "{{ leaf2 }}"
      tags:
        - vpc_pair
    - name: Configure Interface to Router
      cisco.dcnm.dcnm_interface:
        fabric: "{{ fabric_name }}"
        state: replaced
        config:
        # All leafs
          - name: Ethernet1/3
            type: eth
            switch:
              - "{{ leaf3 }}"
            deploy: true
            profile:
              admin_state: true
              mode: routed
              cmds:
                - no shutdown
              description: End-Host 
      tags:
        - interfaces
    - name: Configure Server Ethernet 1/4 Host Interfaces
      cisco.dcnm.dcnm_interface:
        fabric: "{{ fabric_name }}"
        state: replaced
        config:
        # All leafs
          - name: Ethernet1/4
            type: eth
            switch:
              - "{{ leaf1 }}"
              - "{{ leaf2 }}"
            deploy: true
            profile:
              admin_state: true
              mode: access
              cmds:
                - no shutdown
              description: End-Host 
      tags:
        - interfaces
    - name: Create vPC interfaces
      cisco.dcnm.dcnm_interface:
        fabric: "{{ fabric_name }}"
        state: merged
        config:
          - name: vpc101
            type: vpc
            switch:
              - "{{ leaf1 }}"
              - "{{ leaf2 }}"
            deploy: true
            profile:
              admin_state: true
              mode: access
              peer1_pcid: 101
              peer2_pcid: 101
              peer1_members:
                - e1/3
              peer2_members:
                - e1/3
              pc_mode: 'active'
              bpdu_guard: true
              port_type_fast: true
              mtu: jumbo
              peer1_allowed_vlans: none
              peer2_allowed_vlans: none
              peer1_description: "vPC to Ubuntu"
              peer2_description: "vPC to Ubuntu"
      tags:
        - interfaces
    - name: Recalculate
      cisco.dcnm.dcnm_rest:
        method: POST
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/config-save"
        json_data: "{{ {} | to_json }}"
      tags:
        - rnd
    - name: Deploy
      cisco.dcnm.dcnm_rest:
        method: POST
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/config-deploy"
        json_data: "{{ {} | to_json }}"
      tags:
        - rnd